// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: elog.proto

#include "elog.pb.h"
#include "elog.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace elog_grpc {

static const char* ELogGRPCService_method_names[] = {
  "/elog_grpc.ELogGRPCService/SendLogRecord",
  "/elog_grpc.ELogGRPCService/StreamLogRecords",
};

std::unique_ptr< ELogGRPCService::Stub> ELogGRPCService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ELogGRPCService::Stub> stub(new ELogGRPCService::Stub(channel, options));
  return stub;
}

ELogGRPCService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendLogRecord_(ELogGRPCService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamLogRecords_(ELogGRPCService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::Status ELogGRPCService::Stub::SendLogRecord(::grpc::ClientContext* context, const ::elog_grpc::ELogGRPCRecordMsg& request, ::elog_grpc::ELogGRPCStatus* response) {
  return ::grpc::internal::BlockingUnaryCall< ::elog_grpc::ELogGRPCRecordMsg, ::elog_grpc::ELogGRPCStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendLogRecord_, context, request, response);
}

void ELogGRPCService::Stub::async::SendLogRecord(::grpc::ClientContext* context, const ::elog_grpc::ELogGRPCRecordMsg* request, ::elog_grpc::ELogGRPCStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::elog_grpc::ELogGRPCRecordMsg, ::elog_grpc::ELogGRPCStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendLogRecord_, context, request, response, std::move(f));
}

void ELogGRPCService::Stub::async::SendLogRecord(::grpc::ClientContext* context, const ::elog_grpc::ELogGRPCRecordMsg* request, ::elog_grpc::ELogGRPCStatus* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendLogRecord_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::elog_grpc::ELogGRPCStatus>* ELogGRPCService::Stub::PrepareAsyncSendLogRecordRaw(::grpc::ClientContext* context, const ::elog_grpc::ELogGRPCRecordMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::elog_grpc::ELogGRPCStatus, ::elog_grpc::ELogGRPCRecordMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendLogRecord_, context, request);
}

::grpc::ClientAsyncResponseReader< ::elog_grpc::ELogGRPCStatus>* ELogGRPCService::Stub::AsyncSendLogRecordRaw(::grpc::ClientContext* context, const ::elog_grpc::ELogGRPCRecordMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendLogRecordRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientWriter< ::elog_grpc::ELogGRPCRecordMsg>* ELogGRPCService::Stub::StreamLogRecordsRaw(::grpc::ClientContext* context, ::elog_grpc::ELogGRPCStatus* response) {
  return ::grpc::internal::ClientWriterFactory< ::elog_grpc::ELogGRPCRecordMsg>::Create(channel_.get(), rpcmethod_StreamLogRecords_, context, response);
}

void ELogGRPCService::Stub::async::StreamLogRecords(::grpc::ClientContext* context, ::elog_grpc::ELogGRPCStatus* response, ::grpc::ClientWriteReactor< ::elog_grpc::ELogGRPCRecordMsg>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::elog_grpc::ELogGRPCRecordMsg>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamLogRecords_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::elog_grpc::ELogGRPCRecordMsg>* ELogGRPCService::Stub::AsyncStreamLogRecordsRaw(::grpc::ClientContext* context, ::elog_grpc::ELogGRPCStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::elog_grpc::ELogGRPCRecordMsg>::Create(channel_.get(), cq, rpcmethod_StreamLogRecords_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::elog_grpc::ELogGRPCRecordMsg>* ELogGRPCService::Stub::PrepareAsyncStreamLogRecordsRaw(::grpc::ClientContext* context, ::elog_grpc::ELogGRPCStatus* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::elog_grpc::ELogGRPCRecordMsg>::Create(channel_.get(), cq, rpcmethod_StreamLogRecords_, context, response, false, nullptr);
}

ELogGRPCService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ELogGRPCService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ELogGRPCService::Service, ::elog_grpc::ELogGRPCRecordMsg, ::elog_grpc::ELogGRPCStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ELogGRPCService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::elog_grpc::ELogGRPCRecordMsg* req,
             ::elog_grpc::ELogGRPCStatus* resp) {
               return service->SendLogRecord(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ELogGRPCService_method_names[1],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< ELogGRPCService::Service, ::elog_grpc::ELogGRPCRecordMsg, ::elog_grpc::ELogGRPCStatus>(
          [](ELogGRPCService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::elog_grpc::ELogGRPCRecordMsg>* reader,
             ::elog_grpc::ELogGRPCStatus* resp) {
               return service->StreamLogRecords(ctx, reader, resp);
             }, this)));
}

ELogGRPCService::Service::~Service() {
}

::grpc::Status ELogGRPCService::Service::SendLogRecord(::grpc::ServerContext* context, const ::elog_grpc::ELogGRPCRecordMsg* request, ::elog_grpc::ELogGRPCStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ELogGRPCService::Service::StreamLogRecords(::grpc::ServerContext* context, ::grpc::ServerReader< ::elog_grpc::ELogGRPCRecordMsg>* reader, ::elog_grpc::ELogGRPCStatus* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace elog_grpc

