// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: elog.proto
#ifndef GRPC_elog_2eproto__INCLUDED
#define GRPC_elog_2eproto__INCLUDED

#include "elog.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace elog_grpc {

// Interface exported by the server.
class ELogGRPCService final {
 public:
  static constexpr char const* service_full_name() {
    return "elog_grpc.ELogGRPCService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a log record to the server.
    virtual ::grpc::Status SendLogRecord(::grpc::ClientContext* context, const ::elog_grpc::ELogGRPCRecordMsg& request, ::elog_grpc::ELogGRPCStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::elog_grpc::ELogGRPCStatus>> AsyncSendLogRecord(::grpc::ClientContext* context, const ::elog_grpc::ELogGRPCRecordMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::elog_grpc::ELogGRPCStatus>>(AsyncSendLogRecordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::elog_grpc::ELogGRPCStatus>> PrepareAsyncSendLogRecord(::grpc::ClientContext* context, const ::elog_grpc::ELogGRPCRecordMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::elog_grpc::ELogGRPCStatus>>(PrepareAsyncSendLogRecordRaw(context, request, cq));
    }
    // Sends a stream of log records to the server
    std::unique_ptr< ::grpc::ClientWriterInterface< ::elog_grpc::ELogGRPCRecordMsg>> StreamLogRecords(::grpc::ClientContext* context, ::elog_grpc::ELogGRPCStatus* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::elog_grpc::ELogGRPCRecordMsg>>(StreamLogRecordsRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::elog_grpc::ELogGRPCRecordMsg>> AsyncStreamLogRecords(::grpc::ClientContext* context, ::elog_grpc::ELogGRPCStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::elog_grpc::ELogGRPCRecordMsg>>(AsyncStreamLogRecordsRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::elog_grpc::ELogGRPCRecordMsg>> PrepareAsyncStreamLogRecords(::grpc::ClientContext* context, ::elog_grpc::ELogGRPCStatus* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::elog_grpc::ELogGRPCRecordMsg>>(PrepareAsyncStreamLogRecordsRaw(context, response, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Sends a log record to the server.
      virtual void SendLogRecord(::grpc::ClientContext* context, const ::elog_grpc::ELogGRPCRecordMsg* request, ::elog_grpc::ELogGRPCStatus* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendLogRecord(::grpc::ClientContext* context, const ::elog_grpc::ELogGRPCRecordMsg* request, ::elog_grpc::ELogGRPCStatus* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Sends a stream of log records to the server
      virtual void StreamLogRecords(::grpc::ClientContext* context, ::elog_grpc::ELogGRPCStatus* response, ::grpc::ClientWriteReactor< ::elog_grpc::ELogGRPCRecordMsg>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::elog_grpc::ELogGRPCStatus>* AsyncSendLogRecordRaw(::grpc::ClientContext* context, const ::elog_grpc::ELogGRPCRecordMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::elog_grpc::ELogGRPCStatus>* PrepareAsyncSendLogRecordRaw(::grpc::ClientContext* context, const ::elog_grpc::ELogGRPCRecordMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientWriterInterface< ::elog_grpc::ELogGRPCRecordMsg>* StreamLogRecordsRaw(::grpc::ClientContext* context, ::elog_grpc::ELogGRPCStatus* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::elog_grpc::ELogGRPCRecordMsg>* AsyncStreamLogRecordsRaw(::grpc::ClientContext* context, ::elog_grpc::ELogGRPCStatus* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::elog_grpc::ELogGRPCRecordMsg>* PrepareAsyncStreamLogRecordsRaw(::grpc::ClientContext* context, ::elog_grpc::ELogGRPCStatus* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendLogRecord(::grpc::ClientContext* context, const ::elog_grpc::ELogGRPCRecordMsg& request, ::elog_grpc::ELogGRPCStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::elog_grpc::ELogGRPCStatus>> AsyncSendLogRecord(::grpc::ClientContext* context, const ::elog_grpc::ELogGRPCRecordMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::elog_grpc::ELogGRPCStatus>>(AsyncSendLogRecordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::elog_grpc::ELogGRPCStatus>> PrepareAsyncSendLogRecord(::grpc::ClientContext* context, const ::elog_grpc::ELogGRPCRecordMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::elog_grpc::ELogGRPCStatus>>(PrepareAsyncSendLogRecordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriter< ::elog_grpc::ELogGRPCRecordMsg>> StreamLogRecords(::grpc::ClientContext* context, ::elog_grpc::ELogGRPCStatus* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::elog_grpc::ELogGRPCRecordMsg>>(StreamLogRecordsRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::elog_grpc::ELogGRPCRecordMsg>> AsyncStreamLogRecords(::grpc::ClientContext* context, ::elog_grpc::ELogGRPCStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::elog_grpc::ELogGRPCRecordMsg>>(AsyncStreamLogRecordsRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::elog_grpc::ELogGRPCRecordMsg>> PrepareAsyncStreamLogRecords(::grpc::ClientContext* context, ::elog_grpc::ELogGRPCStatus* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::elog_grpc::ELogGRPCRecordMsg>>(PrepareAsyncStreamLogRecordsRaw(context, response, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendLogRecord(::grpc::ClientContext* context, const ::elog_grpc::ELogGRPCRecordMsg* request, ::elog_grpc::ELogGRPCStatus* response, std::function<void(::grpc::Status)>) override;
      void SendLogRecord(::grpc::ClientContext* context, const ::elog_grpc::ELogGRPCRecordMsg* request, ::elog_grpc::ELogGRPCStatus* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StreamLogRecords(::grpc::ClientContext* context, ::elog_grpc::ELogGRPCStatus* response, ::grpc::ClientWriteReactor< ::elog_grpc::ELogGRPCRecordMsg>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::elog_grpc::ELogGRPCStatus>* AsyncSendLogRecordRaw(::grpc::ClientContext* context, const ::elog_grpc::ELogGRPCRecordMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::elog_grpc::ELogGRPCStatus>* PrepareAsyncSendLogRecordRaw(::grpc::ClientContext* context, const ::elog_grpc::ELogGRPCRecordMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientWriter< ::elog_grpc::ELogGRPCRecordMsg>* StreamLogRecordsRaw(::grpc::ClientContext* context, ::elog_grpc::ELogGRPCStatus* response) override;
    ::grpc::ClientAsyncWriter< ::elog_grpc::ELogGRPCRecordMsg>* AsyncStreamLogRecordsRaw(::grpc::ClientContext* context, ::elog_grpc::ELogGRPCStatus* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::elog_grpc::ELogGRPCRecordMsg>* PrepareAsyncStreamLogRecordsRaw(::grpc::ClientContext* context, ::elog_grpc::ELogGRPCStatus* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendLogRecord_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamLogRecords_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a log record to the server.
    virtual ::grpc::Status SendLogRecord(::grpc::ServerContext* context, const ::elog_grpc::ELogGRPCRecordMsg* request, ::elog_grpc::ELogGRPCStatus* response);
    // Sends a stream of log records to the server
    virtual ::grpc::Status StreamLogRecords(::grpc::ServerContext* context, ::grpc::ServerReader< ::elog_grpc::ELogGRPCRecordMsg>* reader, ::elog_grpc::ELogGRPCStatus* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendLogRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendLogRecord() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendLogRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendLogRecord(::grpc::ServerContext* /*context*/, const ::elog_grpc::ELogGRPCRecordMsg* /*request*/, ::elog_grpc::ELogGRPCStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendLogRecord(::grpc::ServerContext* context, ::elog_grpc::ELogGRPCRecordMsg* request, ::grpc::ServerAsyncResponseWriter< ::elog_grpc::ELogGRPCStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamLogRecords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamLogRecords() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_StreamLogRecords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamLogRecords(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::elog_grpc::ELogGRPCRecordMsg>* /*reader*/, ::elog_grpc::ELogGRPCStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamLogRecords(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::elog_grpc::ELogGRPCStatus, ::elog_grpc::ELogGRPCRecordMsg>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(1, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendLogRecord<WithAsyncMethod_StreamLogRecords<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendLogRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendLogRecord() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::elog_grpc::ELogGRPCRecordMsg, ::elog_grpc::ELogGRPCStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::elog_grpc::ELogGRPCRecordMsg* request, ::elog_grpc::ELogGRPCStatus* response) { return this->SendLogRecord(context, request, response); }));}
    void SetMessageAllocatorFor_SendLogRecord(
        ::grpc::MessageAllocator< ::elog_grpc::ELogGRPCRecordMsg, ::elog_grpc::ELogGRPCStatus>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::elog_grpc::ELogGRPCRecordMsg, ::elog_grpc::ELogGRPCStatus>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendLogRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendLogRecord(::grpc::ServerContext* /*context*/, const ::elog_grpc::ELogGRPCRecordMsg* /*request*/, ::elog_grpc::ELogGRPCStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendLogRecord(
      ::grpc::CallbackServerContext* /*context*/, const ::elog_grpc::ELogGRPCRecordMsg* /*request*/, ::elog_grpc::ELogGRPCStatus* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamLogRecords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamLogRecords() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackClientStreamingHandler< ::elog_grpc::ELogGRPCRecordMsg, ::elog_grpc::ELogGRPCStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, ::elog_grpc::ELogGRPCStatus* response) { return this->StreamLogRecords(context, response); }));
    }
    ~WithCallbackMethod_StreamLogRecords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamLogRecords(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::elog_grpc::ELogGRPCRecordMsg>* /*reader*/, ::elog_grpc::ELogGRPCStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::elog_grpc::ELogGRPCRecordMsg>* StreamLogRecords(
      ::grpc::CallbackServerContext* /*context*/, ::elog_grpc::ELogGRPCStatus* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendLogRecord<WithCallbackMethod_StreamLogRecords<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendLogRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendLogRecord() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendLogRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendLogRecord(::grpc::ServerContext* /*context*/, const ::elog_grpc::ELogGRPCRecordMsg* /*request*/, ::elog_grpc::ELogGRPCStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamLogRecords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamLogRecords() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_StreamLogRecords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamLogRecords(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::elog_grpc::ELogGRPCRecordMsg>* /*reader*/, ::elog_grpc::ELogGRPCStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendLogRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendLogRecord() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendLogRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendLogRecord(::grpc::ServerContext* /*context*/, const ::elog_grpc::ELogGRPCRecordMsg* /*request*/, ::elog_grpc::ELogGRPCStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendLogRecord(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamLogRecords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamLogRecords() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_StreamLogRecords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamLogRecords(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::elog_grpc::ELogGRPCRecordMsg>* /*reader*/, ::elog_grpc::ELogGRPCStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamLogRecords(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(1, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendLogRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendLogRecord() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendLogRecord(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendLogRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendLogRecord(::grpc::ServerContext* /*context*/, const ::elog_grpc::ELogGRPCRecordMsg* /*request*/, ::elog_grpc::ELogGRPCStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendLogRecord(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamLogRecords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamLogRecords() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->StreamLogRecords(context, response); }));
    }
    ~WithRawCallbackMethod_StreamLogRecords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamLogRecords(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::elog_grpc::ELogGRPCRecordMsg>* /*reader*/, ::elog_grpc::ELogGRPCStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* StreamLogRecords(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendLogRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendLogRecord() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::elog_grpc::ELogGRPCRecordMsg, ::elog_grpc::ELogGRPCStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::elog_grpc::ELogGRPCRecordMsg, ::elog_grpc::ELogGRPCStatus>* streamer) {
                       return this->StreamedSendLogRecord(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendLogRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendLogRecord(::grpc::ServerContext* /*context*/, const ::elog_grpc::ELogGRPCRecordMsg* /*request*/, ::elog_grpc::ELogGRPCStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendLogRecord(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::elog_grpc::ELogGRPCRecordMsg,::elog_grpc::ELogGRPCStatus>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendLogRecord<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendLogRecord<Service > StreamedService;
};

}  // namespace elog_grpc


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_elog_2eproto__INCLUDED
